TodoApp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.Home,name='home'),
    path('form/',views.Form,name='form'),
    path('details/<int:id>',views.Details,name='details'),
    path('update/<int:id>',views.Update,name='update'),
    path('delete/<int:id>',views.Delete,name='delete'),
]

Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')),
    path('auth/',include('userarauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userarauth/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),

    
    
]

TodoApp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=30)
    language=models.CharField(max_length=30)
    duration=models.CharField(max_length=10)
    image=models.ImageField(upload_to='todoimage')
    description=models.CharField(max_length=200)
    def __str__(self):
        return self.name

userarauth/models.py
from django.db import models

# Create your models here.

TodoApp/forms.py
from .models import Movie
from django import forms

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

TodoApp/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

def Home(req):
    movies=Movie.objects.all()
    return render(req,'index.html',{'movies':movies})
def Form(req):
    if req.method=="POST": 
        name=req.POST.get('name','')
        language=req.POST.get('language','')
        duration=req.POST.get('duration','')
        image=req.FILES['image']
        description=req.POST.get('description','')        
        movie=Movie(name=name,language=language,duration=duration,image=image,description=description)
        movie.save()
        return redirect('home')
    return render(req,'form.html')



def Details(req,id):
    movies=Movie.objects.get(id=id)
    return render(req,'details.html',{'movie':movies})
def Update(req,id):
    movies=Movie.objects.get(id=id)
    f=MovieForm(req.POST,req.FILES or None,instance=movies)
    if f.is_valid():
        f.save()
        return redirect('home')
    return render(req,'formUpdate.html',{"movie":movies,'f':f})

def Delete(req,id):
    movies=Movie.objects.get(id=id)
    if req.method=="POST":
        Movie.objects.filter(id=id).delete()
        return redirect('home')
    return render(req,'delete.html',{"movies":movies})

userarauth/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def registerUser(req):
    if req.method=='POST':
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        print(fname,lname,email,username,password,cpassword)
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:login')
        else:
            messages.info(req,"password not matched")
            return redirect('auth:register')
    return render(req, 'registeruser.html')
def loginUser(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
          auth.login(req,user)
          return redirect("home")
        else:
            messages.info(req, "invalidcredentials")
            return redirect('auth:login')
    return render(req, 'loginuser.html')
def logoutUser(req):
    auth.logout(req)
    return redirect("home")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\index.css' %}">
  <link rel="stylesheet" href="{% static 'css\style.css' %}">
  <link rel="stylesheet" href="{% static 'css\sstyle.css' %}">
  <link rel="stylesheet" href="{% static 'css\ssstyle.css' %}">
</head>

<body>
  {% include 'nav.html' %}
  {% block content %}

  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="d-flex justisfy-content-center">
            <form action="" method="post" class="form w-50">
                {% csrf_token %}
                <div class="my-3">
                </div>
                <div class="my-3 text-center mx-0">
                    <button class="btn btn-primary">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid ps-0 pe-1 mm-details">
    <div class="card-slot row coolor rounded-bottom   py-5 ">
        <!-- imagecard -->
        <div class=" col-6  col-md-2 cardsss ">
            <img class="card-img-top rounded-3" src="{{ movie.image.url }}" alt="Card image cap">
        </div>
        <!-- moviename -->
        <div class="col ps-2 pt-2 ms-5 mt-5 ">
            <div class="row text-light ps-3">

                <h6 class="ps-2  m-0">Playlist</h6>
                <h1 class="namedetail p-0 m-0  ">{{ movie.name }}</h1>
            </div>
            <div class="row  mt-3 ps-2">
                <h6 class="text-light movie-descrition">{{movie.description}}</h6>
            </div>
            <div class="row ps-2">
                <div class="col mt-2 text-light">
                    <h6 class="m-0 p-0 detailsimage">Spotify • 10,100,100 likes • 999 songs, over {{movie.duration}}</h6>
                </div>
            </div>
            <div class="row ps-2">
                <div class="col">
                    <a href="/update/{{movie.id}}" class="btn btn-success ms-2 mt-3 px-5  text-light  ">update</a>
                    <a href="/delete/{{movie.id}}" class="btn btn-danger ms-2 mt-3 px-5  text-light  ">delete</a>
                </div>
            </div> 
        </div>
    </div>
</div>



{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block content %}

<div class="container ">
    <form class="border rounded-2 mt-5 w-75 mx-auto mb-2" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center py-3 ">
            <h3>ADD SONGS HERE</h3> 
        {% comment %} {% endcomment %} 
        <span class="ps-5 ms-5 "></span>
        <input class="form-control w-75 mx-auto mb-2" type="text" name="name" placeholder="Song name">
        <span class="ps-5 ms-5"></span>
        <input class="form-control w-75 mx-auto  mb-2" type="text" name="language" placeholder="Language">
        <span class="ps-5 ms-5"></span>
        <input class="form-control w-75 mx-auto  mb-2" type="text" name="duration" placeholder="Duration">
        <span class="ps-5 ms-5"></span>
        <input class="form-control w-75 mx-auto  mb-2" type="file" name="image" placeholder="SongPoster">
        <span class="ps-5 ms-5"></span>
        <input class="form-control w-75 mx-auto  mb-2" type="text" name="description" placeholder="song Description">

        <button class="btn btn-success my-3  add_button " style="margin-left: 450px;">ADD</button>
        
    </form>

</div>



{% endblock %}

templates/formUpdate.html
{% extends 'base.html' %}
{% block content %}
<form class="xx mx-auto" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{f.as_p}}
    <input type="submit" value="Update" required>
</form>
<style scoped>
    .xx {
        background-color: rgb(30, 30, 31) !important;
        color: white;
        width: 500px !important;
        height: 100% !important;
    }

    input[type="submit"] {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    form {
        max-width: 400px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }
</style>
</div>
</div>
</div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row bb2  ">
    <div class="col-12 ms-0 bb2c h-100 rounded-bottom ">
        <h4 class=" spotify_playlist ms-0 mt-1">
            𝘀𝗽𝗼𝘁𝗶𝗳𝘆 𝗽𝗹𝗮𝘆𝗹𝗶𝘀𝘁𝘀
        </h4>

        <div class="row card_holder">
            {% for movie in movies %}
            <div class="card col-6 col-md-3 m-1  ">
                <div class="img_holder">
                    <a href="/details/{{movie.id}}">
                        <img src="{{movie.image.url}}" alt="">
                    </a>
                </div>
                <div class="Song_Name">
                    <h4>{{movie.name}}</h4>
                    <p>{{movie.description}} </p>
                </div>
                <div class="play-icon">
                    <div class="circle">
                        <div class="triangle">

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/loginuser.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 rounded-3   login_page">
    <form action="" method="post">
        {% csrf_token %}
        <h3 class="login text-center pt-3">𝐋𝐎𝐆𝐈𝐍</h3>
        <div class="form-group login_input  pt-4 ">
            <input type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <div class="form-group  login_input pt-1 ">
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <div class="form-group  login_input  pt-2 ">
            <button type="submit" class="btn btn-primary">𝐋𝐎𝐆𝐈𝐍</button>
        </div>
    </form>
</div>

</div>
</div>
</div>
</div>

{% endblock %}

templates/nav.html
{% load static %}
<!-- side navbaar html -->
<div class="main">
  <div class="container-fluid firstcontainer">
    <div class="row A">
      <div class="col-3 aa">
        <div class="row aaa1 position-fixed">
          <div class="col-12 aaa1a m-1 pt-2  rounded-2 ">
            <div class="ss fs-5 pb-2 "> <a class="text-white text-decoration-none" href="{% url 'home' %}"><img
                  src="{% static './image/icon.png' %}" width="28px" alt="">
                  Ｓｐｏｔｉｆｙ</a>
            </div>
            <div class=" ss2_home fs-5 pb-2"><svg xmlns="http://www.w3.org/2000/svg" class="mtt" height="24"
                viewBox="0 -960 960 960" width="24">
                <path
                  d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z"
                  fill="white" />
              </svg>𝐇𝐎𝐌𝐄</div>
            <div class="ss2  fs-5 pb-2 mt-2"><svg xmlns="http://www.w3.org/2000/svg" class="mtt1" height="24"
                viewBox="0 -960 960 960" width="24">
                <path
                  d="M784-120 532-372q-30 24-69 38t-83 14q-109 0-184.5-75.5T120-580q0-109 75.5-184.5T380-840q109 0 184.5 75.5T640-580q0 44-14 83t-38 69l252 252-56 56ZM380-400q75 0 127.5-52.5T560-580q0-75-52.5-127.5T380-760q-75 0-127.5 52.5T200-580q0 75 52.5 127.5T380-400Z"
                  fill="white" />
              </svg>
              𝗦𝗘𝗔𝗥𝗖𝗛</div>
          </div>
          <!-- libraray -->
          <a href="{% url 'form' %}"
            class="col-12 aaa1b mx-1 mb-1 text-decoration-none flex-end rounded-2 text-white"><svg
              xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="26">
              <path fill="white"
                d="M358.386-424.616h196.921v-45.383H358.386v45.383Zm0-98.077h353.843v-45.384H358.386v45.384Zm0-98.078h353.843v-45.383H358.386v45.383Zm-79.923 390q-23.529 0-40.611-17.082-17.081-17.082-17.081-40.611v-513.842q0-23.529 17.081-40.611 17.082-17.082 40.611-17.082h513.843q23.528 0 40.61 17.082t17.082 40.611v513.842q0 23.529-17.082 40.611-17.082 17.082-40.61 17.082H278.463Zm0-45.384h513.843q4.615 0 8.462-3.846 3.846-3.847 3.846-8.463v-513.842q0-4.616-3.846-8.463-3.847-3.846-8.462-3.846H278.463q-4.616 0-8.462 3.846-3.847 3.847-3.847 8.463v513.842q0 4.616 3.847 8.463 3.846 3.846 8.462 3.846ZM167.694-120.003q-23.528 0-40.61-17.082-17.082-17.081-17.082-40.61v-559.226h45.384v559.226q0 4.616 3.846 8.462 3.847 3.847 8.462 3.847h559.227v45.383H167.694Zm98.46-694.612V-276.155-814.615Z" />
            </svg>&nbsp;𝗔𝗗𝗗 𝗦𝗢𝗡𝗚𝗦 𝗛𝗘𝗥𝗘&nbsp;+</a>
        </div>
      </div>
      <div class="col-9 bb ">
        <div class="row bb1 ">
          <div class="col-12 bb1c px-0 ms-0  mt-1 mt-md-0 ">
            <nav class="navbar  navbar-expand-lg navbar-light px-0  ">
              <!-- Button to toggle the navbar on smaller screens -->
              <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse  rounded-top navbar-collapse mt-md-0 mt-2 bg-dark" id="navbarNav">
                <ul class="navbar-nav  pt-1  fw-bold  pb-2 ms-auto ">
                  <!-- Premium link -->
                  <li class="nav-item">
                    <a class="nav-link  " href="#">𝗣𝗿𝗲𝗺𝗶𝘂𝗺
                    </a>
                  </li>

                  <!-- Support link -->
                  <li class="nav-item">
                    <a class="nav-link" href="#">𝗦𝘂𝗽𝗽𝗼𝗿𝘁</a>
                  </li>

                  <!-- Download link -->

                  <li class="nav-item">
                    <a class="nav-link border-end border-secondary border-2 pe-4 me-4" href="#">𝗗𝗼𝘄𝗻𝗹𝗼𝗮𝗱</a>
                  </li>
                  {% if user.is_authenticated %}
                  <span>{{user}}</span>
                  <li class="nav-item ">
                    <a class="nav-link nav-signup btn mb-lg-0 mb-2" href="{% url 'auth:logout' %}"><b>𝗟𝗼𝗴𝗼𝘂𝘁</b></a>
                  </li>

                  {% else %}
                  <li class="nav-item ">
                    <a class="nav-link nav-signup btn mb-lg-0 mb-2" href="{% url 'auth:register' %}"><b>𝗦𝗶𝗴𝗻 𝘂𝗽</b></a>
                  </li>
                  <li class="nav-item ">
                    <a class=" nav-bttn btn px-3 py-2 rounded-pill btn-outline-dark mx-lg-3 mx-0 "
                      href="{% url 'auth:login' %}"><b>𝗟𝗢𝗚𝗜𝗡 𝗛𝗘𝗥𝗘</b></a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </nav>
          </div>
        </div>

templates/registeruser.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" class="bg-green p-3 mt-2 rounded mx-5">
    {% csrf_token %}
    <h2 class="signup text-center">𝗦𝗜𝗚𝗡𝗨𝗣</h2>
    <div class="mb-3">
        <label for="fname" class="form-label">FIRST NAME </label>
        <input type="text" class="form-control" id="fname" placeholder="First Name" name="fname">
    </div>
    <div class="mb-3">
        <label for="lname" class="form-label">LAST NAME</label>
        <input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">EMAIL ID </label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">USER NAME</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">PASSWORD</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="mb-3">
        <label for="cpassword" class="form-label">CONFIRM PASSWORD</label>
        <input type="password" class="form-control" id="cpassword" placeholder="Confirm Password" name="cpassword">
    </div>
    <div>
        <button type="submit" class="btn btn-primary">SUBMIT</button>
    </div>
</form>

{% endblock %}